name: 'SDK'
description: 'Creates SDK and Uploads artifacts'
inputs:
  shell:
    required: false
    default: bash
    type: string
  package-name:
    default: febio
    required: false
    type: string
  script:
    required: true
    type: string
  os:
    required: true
    type: string
  arch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Create SDK
      shell: ${{ inputs.shell }}
      env:
        TARGET_DIR: ${{ inputs.package-name }}-sdk
      run: |
        ci/${{inputs.os}}/create-sdk.sh
    - name: Upload SDK
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.package-name }}-sdk-${{inputs.os}}-${{inputs.arch}}
        path: |
          ${{ inputs.package-name }}-sdk
